name: On Push Run

on: push

env:
  DEVOPS_DIR: devops

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        pip install beautifulsoup4

    - name: Hello World
      run: python $GITHUB_WORKSPACE/app.py
      shell: sh
